name: Calculator

on:
  workflow_dispatch:
    inputs:
      usrInput1:
        description: Take User Input 1
        default: '0'
        required: true
      usrInput2:
        description: Take User Input 2
        default: '0'
        required: true
      operator:
        type: choice
        description: Choose Operator
        options:
        - multiply
        - addition
        - substraction
        - division

jobs:
  perform-operation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Multiply
        if: github.event.inputs.operator == 'multiply'
        run: |
            let x = ${{github.event.inputs.usrInput1}}
            let y = ${{github.event.inputs.usrInput2}}
            let res = $(expr $x \* $y)
            echo "Result is : $res"
      - name: Addition
        if: github.event.inputs.operator == 'addition'
        run: |
            let x = ${{github.event.inputs.usrInput1}}
            let y = ${{github.event.inputs.usrInput2}}
            let res = $(expr $x + $y)
            echo "Result is : $res"
      - name: Substraction
        if: github.event.inputs.operator == 'substraction'
        run: |
            let x = ${{github.event.inputs.usrInput1}}
            let y = ${{github.event.inputs.usrInput2}}
            let res = $(expr $x - $y)
            echo "Result is : $res"
      - name: Division
        if: github.event.inputs.operator == 'division'
        run: |
            let x = ${{github.event.inputs.usrInput1}}
            let y = ${{github.event.inputs.usrInput2}}
            let res = $(expr $x / $y)
            echo "Result is: $res"
            
    
