name: Calculator

on:
  workflow_dispatch:
    inputs:
      usrInput1:
        type: number
        description: Take User Input 1
        default: '0'
        required: true
      usrInput2:
        type: number
        description: Take User Input 2
        default: '0'
        required: true
      operator:
        type: choice
        required: true
        description: Choose Operator
        options:
        - '*'
        - '+'
        - '-'
        - '/'

jobs:
  perform_operation:
    runs-on: windows-latest
    outputs:
      my_output: ${{ steps.output.outputs.my_output }}
    steps:
      - run: |
          $result = ${{ inputs.usrInput1 }}${{ inputs.operator }}${{ inputs.usrInput2 }}
          echo result = $result >> $env:GITHUB_OUTPUT
          id: output
        
  output:
    needs: perform_operation
    runs-on: windows-latest
    steps:
      - name: output
        run: echo "${{ needs.perform-operation.outputs.my_output }}"
    
        
    
    
