name: Calculator

on:
  workflow_dispatch:
    inputs:
      usrInput1:
        description: Take User Input 1
        default: '0'
        required: true
      usrInput2:
        description: Take User Input 2
        default: '0'
        required: true
      operator:
        type: choice
        description: Choose Operator
        options:
        - multiply
        - addition
        - substraction
        - division

jobs:
  perform-operation:
    runs-on: windows-latest
    outputs:
      my_output: ${{ steps.id.outputs.my_step_output }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Multiply
        id: ${{ github.event.inputs.operator }}
        if: github.event.inputs.operator == 'multiply'
        run: echo "::set-output name=my_step_output::$(( github.event.inputs.usrInput1*github.event.inputs.usrInput2 ))"
             
      - name: Addition
        id: ${{ github.event.inputs.operator }}
        if: github.event.inputs.operator == 'addition'
        run: echo "::set-output name=my_step_output::$(( ${{github.event.inputs.usrInput1}}+${{github.event.inputs.usrInput2}} ))"
        
      - name: Substraction
        id: ${{ github.event.inputs.operator }}
        if: github.event.inputs.operator == 'substraction'
        run: echo "::set-output name=my_step_output::$(( ${{github.event.inputs.usrInput1}}-${{github.event.inputs.usrInput2}} ))"
        
      - name: Division
        id: ${{ github.event.inputs.operator }}
        if: github.event.inputs.operator == 'division'
        run: echo "::set-output name=my_step_output::$(( ${{github.event.inputs.usrInput1}}/${{github.event.inputs.usrInput2}} ))"
        
  output:
    runs-on: windows-latest
    steps:
      - name: output
        run: echo ${{ jobs.perform-operation.outputs.my_output }}
    
        
    
    
