name: Calculator

on:
  workflow_dispatch:
    inputs:
      usrInput1:
        description: Take User Input 1
        default: '0'
        required: true
      usrInput2:
        description: Take User Input 2
        default: '0'
        required: true
      operator:
        type: choice
        description: Choose Operator
        options:
        - '*'
        - '+'
        - '-'
        - '/'

jobs:
  perform-operation:
    runs-on: windows-latest
    outputs:
      my_output: ${{ steps.id.outputs.my_step_output }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Multiply
        if: github.event.inputs.operator == '*'
        id: multi
        run: $(( ${{github.event.inputs.usrInput1}} \* ${{github.event.inputs.usrInput2}} )) echo 'my_step_output={}' >> $GITHUB_OUTPUT ';'
             
      - name: Addition
        if: github.event.inputs.operator == '+'
        id: add
        run: $(( ${{github.event.inputs.usrInput1}} + ${{github.event.inputs.usrInput2}} )) echo 'my_step_output={}' >> $GITHUB_OUTPUT ';'
        
      - name: Substraction
        if: github.event.inputs.operator == '-'
        id: sub
        run: $(( ${{github.event.inputs.usrInput1}} - ${{github.event.inputs.usrInput2}} )) echo 'my_step_output={}' >> $GITHUB_OUTPUT ';
        
      - name: Division
        if: github.event.inputs.operator == '/'
        id: div
        run: $(( ${{github.event.inputs.usrInput1}} / ${{github.event.inputs.usrInput2}} )) echo 'my_step_output={}' >> $GITHUB_OUTPUT ';
        
  output:
    needs: perform-operation
    runs-on: windows-latest
    steps:
      - name: output
        run: echo "${{ needs.perform-operation.outputs.my_output }}"
    
        
    
    
